// <auto-generated />
using System;
using DotNetCloud.Modules.Tracks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNetCloud.Modules.Tracks.Data.Migrations
{
    [DbContext(typeof(TracksDbContext))]
    [Migration("20260501024146_AddQueryFilters_ProductsWorkItemsComments")]
    partial class AddQueryFilters_ProductsWorkItemsComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_activities_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_activities_entity");

                    b.HasIndex("ProductId", "CreatedAt")
                        .HasDatabaseName("ix_activities_product_created");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.AutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_automation_rules_product_id");

                    b.ToTable("AutomationRules");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Checklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "Position")
                        .HasDatabaseName("ix_checklists_item_position");

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_checklist_items_assigned_to")
                        .HasFilter("\"AssignedToUserId\" IS NOT NULL");

                    b.HasIndex("ChecklistId", "Position")
                        .HasDatabaseName("ix_checklist_items_checklist_position");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CommentReaction", b =>
                {
                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Emoji")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CommentId", "UserId", "Emoji");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_comment_reactions_comment");

                    b.ToTable("CommentReactions");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OptionsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_custom_fields_product_name");

                    b.ToTable("CustomFields");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CustomView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("GroupBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SortJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "UserId", "Name")
                        .IsUnique();

                    b.ToTable("CustomViews", "tracks");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("CurrentValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentGoalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProgressType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("TargetValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentGoalId")
                        .HasDatabaseName("ix_goals_parent_goal_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_goals_product_id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.GoalWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId");

                    b.HasIndex("GoalId", "WorkItemId")
                        .IsUnique()
                        .HasDatabaseName("uq_goal_workitem");

                    b.ToTable("GoalWorkItems");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.GuestPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GuestUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Permission")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId");

                    b.HasIndex("GuestUserId", "WorkItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_permissions_guest_work_item");

                    b.ToTable("GuestPermissions");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.GuestUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("InviteToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_guest_users_email");

                    b.HasIndex("InviteToken")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_users_invite_token");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_guest_users_product");

                    b.ToTable("GuestUsers");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChecklistsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LabelIdsJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("TitlePattern")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_item_templates_product_id");

                    b.ToTable("ItemTemplates");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Title")
                        .IsUnique()
                        .HasDatabaseName("uq_labels_product_title");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Upcoming");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Title")
                        .IsUnique()
                        .HasDatabaseName("uq_milestones_product_title");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.PokerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptedEstimate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomScaleValues")
                        .HasColumnType("text");

                    b.Property<Guid>("EpicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Round")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Scale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_poker_sessions_created_by");

                    b.HasIndex("ReviewSessionId")
                        .HasDatabaseName("ix_poker_sessions_review_session")
                        .HasFilter("\"ReviewSessionId\" IS NOT NULL");

                    b.HasIndex("EpicId", "Status")
                        .HasDatabaseName("ix_poker_sessions_epic_status");

                    b.HasIndex("ItemId", "Status")
                        .HasDatabaseName("ix_poker_sessions_item_status");

                    b.ToTable("PokerSessions");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.PokerVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estimate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("VotedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_poker_votes_user");

                    b.HasIndex("SessionId", "UserId", "Round")
                        .IsUnique()
                        .HasDatabaseName("ix_poker_votes_session_user_round");

                    b.ToTable("PokerVotes");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SubItemsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_products_created_at");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_products_is_archived");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_products_is_deleted");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_products_organization_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_products_owner_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ProductMember", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ProductId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_product_members_user_id");

                    b.HasIndex("ProductId", "Role")
                        .HasDatabaseName("ix_product_members_product_role");

                    b.ToTable("ProductMembers");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ProductTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_product_templates_category");

                    b.HasIndex("IsBuiltIn")
                        .HasDatabaseName("ix_product_templates_is_built_in");

                    b.ToTable("ProductTemplates");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.RecurringRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SwimlaneId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("NextRunAt")
                        .HasDatabaseName("ix_recurring_rules_next_run");

                    b.HasIndex("ProductId");

                    b.HasIndex("SwimlaneId");

                    b.ToTable("RecurringRules");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ReviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CurrentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EpicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("CurrentItemId");

                    b.HasIndex("HostUserId")
                        .HasDatabaseName("ix_review_sessions_host_user_id");

                    b.HasIndex("EpicId", "Status")
                        .HasDatabaseName("ix_review_sessions_epic_status");

                    b.ToTable("ReviewSessions");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ReviewSessionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ReviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_review_session_participants_user_id");

                    b.HasIndex("ReviewSessionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_review_session_participants_session_user");

                    b.ToTable("ReviewSessionParticipants");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EpicId")
                        .HasColumnType("uuid");

                    b.Property<string>("Goal")
                        .HasColumnType("text");

                    b.Property<int?>("PlannedOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TargetStoryPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_sprints_start_date")
                        .HasFilter("\"StartDate\" IS NOT NULL");

                    b.HasIndex("EpicId", "Status")
                        .HasDatabaseName("ix_sprints_epic_status");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.SprintItem", b =>
                {
                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("SprintId", "ItemId");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_sprint_items_item_id");

                    b.ToTable("SprintItems");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Swimlane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CardLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_swimlanes_is_archived");

                    b.HasIndex("ProductId");

                    b.HasIndex("ContainerType", "ContainerId", "Position")
                        .HasDatabaseName("ix_swimlanes_container_position");

                    b.ToTable("Swimlanes");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.SwimlaneTransitionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("FromSwimlaneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToSwimlaneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ToSwimlaneId");

                    b.HasIndex("FromSwimlaneId", "ToSwimlaneId")
                        .HasDatabaseName("ix_swimlane_transition_rules_from_to");

                    b.HasIndex("ProductId", "FromSwimlaneId", "ToSwimlaneId")
                        .IsUnique()
                        .HasDatabaseName("ix_swimlane_transition_rules_product_from_to");

                    b.ToTable("SwimlaneTransitionRules");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tracks_teams_name");

                    b.ToTable("TracksTeams", (string)null);
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.TeamRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_team_roles_team_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_team_roles_user_id");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_team_roles_team_user");

                    b.ToTable("TeamRoles");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_time_entries_start_time")
                        .HasFilter("\"StartTime\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_time_entries_user_id");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_time_entries_work_item_id");

                    b.HasIndex("WorkItemId", "UserId")
                        .HasDatabaseName("ix_time_entries_work_item_user");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_webhook_deliveries_created");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_webhook_deliveries_subscription");

                    b.ToTable("WebhookDeliveries");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedDeliveryCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_webhook_subscriptions_active");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_webhook_subscriptions_product");

                    b.ToTable("WebhookSubscriptions");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentWorkItemId")
                        .HasColumnType("uuid");

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecurringRuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SwimlaneId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_work_items_created_at");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_work_items_created_by");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_work_items_due_date")
                        .HasFilter("\"DueDate\" IS NOT NULL");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_work_items_is_archived");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_work_items_is_deleted");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("ParentWorkItemId")
                        .HasDatabaseName("ix_work_items_parent");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_work_items_priority");

                    b.HasIndex("RecurringRuleId");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_work_items_start_date")
                        .HasFilter("\"StartDate\" IS NOT NULL");

                    b.HasIndex("ProductId", "ItemNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_work_items_product_number");

                    b.HasIndex("ProductId", "Type")
                        .HasDatabaseName("ix_work_items_product_type");

                    b.HasIndex("SwimlaneId", "Position")
                        .HasDatabaseName("ix_work_items_swimlane_position");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_work_item_assignments_user_id");

                    b.HasIndex("WorkItemId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_work_item_assignments_item_user");

                    b.ToTable("WorkItemAssignments");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("FileNodeId")
                        .HasColumnType("uuid");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileNodeId")
                        .HasDatabaseName("ix_work_item_attachments_file_node")
                        .HasFilter("\"FileNodeId\" IS NOT NULL");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_work_item_attachments_work_item");

                    b.ToTable("WorkItemAttachments");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_work_item_comments_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_work_item_comments_user");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_work_item_comments_work_item");

                    b.ToTable("WorkItemComments");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DependsOnWorkItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnWorkItemId")
                        .HasDatabaseName("ix_work_item_dependencies_depends_on");

                    b.HasIndex("WorkItemId", "DependsOnWorkItemId", "Type")
                        .IsUnique()
                        .HasDatabaseName("uq_work_item_dependencies_item_depends_type");

                    b.ToTable("WorkItemDependencies");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldId");

                    b.HasIndex("WorkItemId", "CustomFieldId")
                        .IsUnique()
                        .HasDatabaseName("uq_workitem_fieldvalue_item_field");

                    b.ToTable("WorkItemFieldValues");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemLabel", b =>
                {
                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("WorkItemId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("WorkItemLabels");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Permission")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_work_item_share_links_active");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_work_item_share_links_token");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_work_item_share_links_work_item");

                    b.ToTable("WorkItemShareLinks");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemWatcher", b =>
                {
                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkItemId", "UserId");

                    b.ToTable("WorkItemWatchers", "tracks");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Activity", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany("Activities")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.AutomationRule", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Checklist", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "Item")
                        .WithMany("Checklists")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ChecklistItem", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Checklist", "Checklist")
                        .WithMany("Items")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CommentReaction", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItemComment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CustomField", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany("CustomFields")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CustomView", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Goal", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Goal", "ParentGoal")
                        .WithMany("ChildGoals")
                        .HasForeignKey("ParentGoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentGoal");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.GoalWorkItem", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Goal", "Goal")
                        .WithMany("LinkedWorkItems")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "WorkItem")
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.GuestPermission", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.GuestUser", "GuestUser")
                        .WithMany("Permissions")
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "WorkItem")
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuestUser");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.GuestUser", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ItemTemplate", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Label", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany("Labels")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Milestone", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany("Milestones")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.PokerSession", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "Epic")
                        .WithMany()
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "Item")
                        .WithMany("PokerSessions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.ReviewSession", "ReviewSession")
                        .WithMany("PokerSessions")
                        .HasForeignKey("ReviewSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Epic");

                    b.Navigation("Item");

                    b.Navigation("ReviewSession");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.PokerVote", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.PokerSession", "Session")
                        .WithMany("Votes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ProductMember", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany("Members")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.RecurringRule", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany("RecurringRules")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Swimlane", "Swimlane")
                        .WithMany()
                        .HasForeignKey("SwimlaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Swimlane");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ReviewSession", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "CurrentItem")
                        .WithMany()
                        .HasForeignKey("CurrentItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "Epic")
                        .WithMany()
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentItem");

                    b.Navigation("Epic");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ReviewSessionParticipant", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.ReviewSession", "ReviewSession")
                        .WithMany("Participants")
                        .HasForeignKey("ReviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewSession");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Sprint", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "Epic")
                        .WithMany()
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Epic");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.SprintItem", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "Item")
                        .WithMany("SprintItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Sprint", "Sprint")
                        .WithMany("SprintItems")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Swimlane", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", null)
                        .WithMany("Swimlanes")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.SwimlaneTransitionRule", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Swimlane", "FromSwimlane")
                        .WithMany()
                        .HasForeignKey("FromSwimlaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Swimlane", "ToSwimlane")
                        .WithMany()
                        .HasForeignKey("ToSwimlaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromSwimlane");

                    b.Navigation("Product");

                    b.Navigation("ToSwimlane");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.TeamRole", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Team", null)
                        .WithMany("TeamRoles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.TimeEntry", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "WorkItem")
                        .WithMany("TimeEntries")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WebhookDelivery", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WebhookSubscription", "Subscription")
                        .WithMany("Deliveries")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WebhookSubscription", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItem", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Milestone", "Milestone")
                        .WithMany("WorkItems")
                        .HasForeignKey("MilestoneId");

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "ParentWorkItem")
                        .WithMany("ChildWorkItems")
                        .HasForeignKey("ParentWorkItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Product", "Product")
                        .WithMany("WorkItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.RecurringRule", "RecurringRule")
                        .WithMany()
                        .HasForeignKey("RecurringRuleId");

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Swimlane", "Swimlane")
                        .WithMany("WorkItems")
                        .HasForeignKey("SwimlaneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Milestone");

                    b.Navigation("ParentWorkItem");

                    b.Navigation("Product");

                    b.Navigation("RecurringRule");

                    b.Navigation("Swimlane");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemAssignment", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "WorkItem")
                        .WithMany("Assignments")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemAttachment", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "WorkItem")
                        .WithMany("Attachments")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemComment", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "WorkItem")
                        .WithMany("Comments")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemDependency", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "DependsOnWorkItem")
                        .WithMany("Dependents")
                        .HasForeignKey("DependsOnWorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "WorkItem")
                        .WithMany("Dependencies")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnWorkItem");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemFieldValue", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.CustomField", "CustomField")
                        .WithMany("FieldValues")
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "WorkItem")
                        .WithMany("FieldValues")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomField");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemLabel", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Label", "Label")
                        .WithMany("WorkItemLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "WorkItem")
                        .WithMany("WorkItemLabels")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemShareLink", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "WorkItem")
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItemWatcher", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.WorkItem", "WorkItem")
                        .WithMany("Watchers")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Checklist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CustomField", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Goal", b =>
                {
                    b.Navigation("ChildGoals");

                    b.Navigation("LinkedWorkItems");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.GuestUser", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Label", b =>
                {
                    b.Navigation("WorkItemLabels");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Milestone", b =>
                {
                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.PokerSession", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Product", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("CustomFields");

                    b.Navigation("Labels");

                    b.Navigation("Members");

                    b.Navigation("Milestones");

                    b.Navigation("RecurringRules");

                    b.Navigation("Swimlanes");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ReviewSession", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("PokerSessions");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Sprint", b =>
                {
                    b.Navigation("SprintItems");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Swimlane", b =>
                {
                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Team", b =>
                {
                    b.Navigation("TeamRoles");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WebhookSubscription", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.WorkItem", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Attachments");

                    b.Navigation("Checklists");

                    b.Navigation("ChildWorkItems");

                    b.Navigation("Comments");

                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");

                    b.Navigation("FieldValues");

                    b.Navigation("PokerSessions");

                    b.Navigation("SprintItems");

                    b.Navigation("TimeEntries");

                    b.Navigation("Watchers");

                    b.Navigation("WorkItemLabels");
                });
#pragma warning restore 612, 618
        }
    }
}
