// <auto-generated />
using System;
using DotNetCloud.Modules.Tracks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNetCloud.Modules.Tracks.Data.Migrations
{
    [DbContext(typeof(TracksDbContext))]
    [Migration("20260402123149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockSwimlanes")
                        .HasColumnType("boolean");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Personal");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_boards_created_at");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_boards_is_archived");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_boards_is_deleted");

                    b.HasIndex("Mode")
                        .HasDatabaseName("ix_boards_mode");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_boards_owner_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_boards_team_id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.BoardActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_board_activities_user_id");

                    b.HasIndex("BoardId", "CreatedAt")
                        .HasDatabaseName("ix_board_activities_board_created");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_board_activities_entity");

                    b.ToTable("BoardActivities");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.BoardMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_board_members_user_id");

                    b.HasIndex("BoardId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_board_members_board_user");

                    b.ToTable("BoardMembers");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.BoardSwimlane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CardLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_board_swimlanes_is_archived");

                    b.HasIndex("BoardId", "Position")
                        .HasDatabaseName("ix_board_swimlanes_board_position");

                    b.ToTable("BoardSwimlanes");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.BoardTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsBuiltIn");

                    b.ToTable("BoardTemplates");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("SwimlaneId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_cards_card_number");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_cards_created_at");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_cards_created_by");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_cards_due_date")
                        .HasFilter("\"DueDate\" IS NOT NULL");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_cards_is_archived");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_cards_is_deleted");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_cards_priority");

                    b.HasIndex("SwimlaneId", "Position")
                        .HasDatabaseName("ix_cards_swimlane_position");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_card_assignments_user_id");

                    b.HasIndex("CardId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_card_assignments_card_user");

                    b.ToTable("CardAssignments");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("FileNodeId")
                        .HasColumnType("uuid");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_card_attachments_card_id");

                    b.HasIndex("FileNodeId")
                        .HasDatabaseName("ix_card_attachments_file_node_id")
                        .HasFilter("\"FileNodeId\" IS NOT NULL");

                    b.ToTable("CardAttachments");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CardId", "Position")
                        .HasDatabaseName("ix_card_checklists_card_position");

                    b.ToTable("CardChecklists");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_card_comments_card_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_card_comments_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_card_comments_user_id");

                    b.ToTable("CardComments");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DependsOnCardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnCardId")
                        .HasDatabaseName("ix_card_dependencies_depends_on");

                    b.HasIndex("CardId", "DependsOnCardId", "Type")
                        .IsUnique()
                        .HasDatabaseName("uq_card_dependencies_card_depends_type");

                    b.ToTable("CardDependencies");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardLabel", b =>
                {
                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CardId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("CardLabels");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChecklistsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LabelIdsJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TitlePattern")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("CardTemplates");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_checklist_items_assigned_to")
                        .HasFilter("\"AssignedToUserId\" IS NOT NULL");

                    b.HasIndex("ChecklistId", "Position")
                        .HasDatabaseName("ix_checklist_items_checklist_position");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "Title")
                        .IsUnique()
                        .HasDatabaseName("uq_labels_board_title");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.PokerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptedEstimate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomScaleValues")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Round")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Scale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_poker_sessions_created_by");

                    b.HasIndex("ReviewSessionId")
                        .HasDatabaseName("ix_poker_sessions_review_session")
                        .HasFilter("\"ReviewSessionId\" IS NOT NULL");

                    b.HasIndex("BoardId", "Status")
                        .HasDatabaseName("ix_poker_sessions_board_status");

                    b.HasIndex("CardId", "Status")
                        .HasDatabaseName("ix_poker_sessions_card_status");

                    b.ToTable("PokerSessions");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.PokerVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estimate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("VotedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_poker_votes_user");

                    b.HasIndex("SessionId", "UserId", "Round")
                        .IsUnique()
                        .HasDatabaseName("ix_poker_votes_session_user_round");

                    b.ToTable("PokerVotes");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ReviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CurrentCardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCardId");

                    b.HasIndex("HostUserId")
                        .HasDatabaseName("ix_review_sessions_host_user_id");

                    b.HasIndex("BoardId", "Status")
                        .HasDatabaseName("ix_review_sessions_board_status");

                    b.ToTable("ReviewSessions");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ReviewSessionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ReviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_review_session_participants_user_id");

                    b.HasIndex("ReviewSessionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_review_session_participants_session_user");

                    b.ToTable("ReviewSessionParticipants");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Goal")
                        .HasColumnType("text");

                    b.Property<int?>("PlannedOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TargetStoryPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_sprints_start_date")
                        .HasFilter("\"StartDate\" IS NOT NULL");

                    b.HasIndex("BoardId", "Status")
                        .HasDatabaseName("ix_sprints_board_status");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.SprintCard", b =>
                {
                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("SprintId", "CardId");

                    b.HasIndex("CardId");

                    b.ToTable("SprintCards");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.TeamRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CoreTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoreTeamId")
                        .HasDatabaseName("ix_team_roles_core_team_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_team_roles_user_id");

                    b.HasIndex("CoreTeamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_team_roles_team_user");

                    b.ToTable("TeamRoles");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_time_entries_card_id");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_time_entries_start_time")
                        .HasFilter("\"StartTime\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_time_entries_user_id");

                    b.HasIndex("CardId", "UserId")
                        .HasDatabaseName("ix_time_entries_card_user");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.BoardActivity", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Board", "Board")
                        .WithMany("Activities")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.BoardMember", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Board", "Board")
                        .WithMany("Members")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.BoardSwimlane", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Board", "Board")
                        .WithMany("Swimlanes")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Card", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.BoardSwimlane", "Swimlane")
                        .WithMany("Cards")
                        .HasForeignKey("SwimlaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Swimlane");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardAssignment", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Card", "Card")
                        .WithMany("Assignments")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardAttachment", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Card", "Card")
                        .WithMany("Attachments")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardChecklist", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Card", "Card")
                        .WithMany("Checklists")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardComment", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Card", "Card")
                        .WithMany("Comments")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardDependency", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Card", "Card")
                        .WithMany("Dependencies")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Card", "DependsOnCard")
                        .WithMany("Dependents")
                        .HasForeignKey("DependsOnCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("DependsOnCard");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardLabel", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Card", "Card")
                        .WithMany("CardLabels")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Label", "Label")
                        .WithMany("CardLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardTemplate", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ChecklistItem", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.CardChecklist", "Checklist")
                        .WithMany("Items")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Label", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Board", "Board")
                        .WithMany("Labels")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.PokerSession", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Board", "Board")
                        .WithMany("PokerSessions")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Card", "Card")
                        .WithMany("PokerSessions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.ReviewSession", "ReviewSession")
                        .WithMany("PokerSessions")
                        .HasForeignKey("ReviewSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Board");

                    b.Navigation("Card");

                    b.Navigation("ReviewSession");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.PokerVote", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.PokerSession", "Session")
                        .WithMany("Votes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ReviewSession", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Board", "Board")
                        .WithMany("ReviewSessions")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Card", "CurrentCard")
                        .WithMany()
                        .HasForeignKey("CurrentCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Board");

                    b.Navigation("CurrentCard");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ReviewSessionParticipant", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.ReviewSession", "ReviewSession")
                        .WithMany("Participants")
                        .HasForeignKey("ReviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewSession");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Sprint", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Board", "Board")
                        .WithMany("Sprints")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.SprintCard", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Card", "Card")
                        .WithMany("SprintCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Sprint", "Sprint")
                        .WithMany("SprintCards")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.TimeEntry", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Tracks.Models.Card", "Card")
                        .WithMany("TimeEntries")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Board", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Labels");

                    b.Navigation("Members");

                    b.Navigation("PokerSessions");

                    b.Navigation("ReviewSessions");

                    b.Navigation("Sprints");

                    b.Navigation("Swimlanes");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.BoardSwimlane", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Card", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Attachments");

                    b.Navigation("CardLabels");

                    b.Navigation("Checklists");

                    b.Navigation("Comments");

                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");

                    b.Navigation("PokerSessions");

                    b.Navigation("SprintCards");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.CardChecklist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Label", b =>
                {
                    b.Navigation("CardLabels");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.PokerSession", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.ReviewSession", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("PokerSessions");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Tracks.Models.Sprint", b =>
                {
                    b.Navigation("SprintCards");
                });
#pragma warning restore 612, 618
        }
    }
}
