using DotNetCloud.Modules.Files.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DotNetCloud.Modules.Files.Data.Configuration;

/// <summary>
/// EF Core configuration for the <see cref="SyncDevice"/> entity.
/// </summary>
public sealed class SyncDeviceConfiguration : IEntityTypeConfiguration<SyncDevice>
{
    /// <inheritdoc />
    public void Configure(EntityTypeBuilder<SyncDevice> builder)
    {
        builder.HasKey(d => d.Id);

        // Device ID is client-generated, not auto-generated by the DB
        builder.Property(d => d.Id)
            .ValueGeneratedNever();

        builder.Property(d => d.DeviceName)
            .IsRequired()
            .HasMaxLength(255);

        builder.Property(d => d.Platform)
            .HasMaxLength(50);

        builder.Property(d => d.ClientVersion)
            .HasMaxLength(50);

        builder.Property(d => d.FirstSeenAt)
            .IsRequired()
            .HasDefaultValueSql("CURRENT_TIMESTAMP");

        builder.Property(d => d.LastSeenAt)
            .IsRequired()
            .HasDefaultValueSql("CURRENT_TIMESTAMP");

        // Indexes
        builder.HasIndex(d => d.UserId)
            .HasDatabaseName("ix_sync_devices_user_id");

        builder.HasIndex(d => new { d.UserId, d.IsActive })
            .HasDatabaseName("ix_sync_devices_user_active");
    }
}
