using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DotNetCloud.Core.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddSearchIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: the SearchIndexEntries / IndexingJobs tables already exist in
            // production (created by the old Search module migrations). Each DDL
            // statement is guarded so applying this migration on a database that
            // already has the tables is a no-op.
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_namespace WHERE nspname = 'core') THEN
        CREATE SCHEMA core;
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'core' AND tablename = 'IndexingJobs') THEN
        CREATE TABLE core.""IndexingJobs"" (
            ""Id"" uuid NOT NULL,
            ""ModuleId"" varchar(50) NULL,
            ""Type"" varchar(20) NOT NULL,
            ""Status"" varchar(20) NOT NULL,
            ""StartedAt"" timestamptz NULL,
            ""CompletedAt"" timestamptz NULL,
            ""DocumentsProcessed"" integer NOT NULL,
            ""DocumentsTotal"" integer NOT NULL,
            ""ErrorMessage"" varchar(2000) NULL,
            CONSTRAINT ""PK_IndexingJobs"" PRIMARY KEY (""Id"")
        );
        CREATE INDEX ""ix_indexing_jobs_status"" ON core.""IndexingJobs"" (""Status"");
        CREATE INDEX ""ix_indexing_jobs_module_id"" ON core.""IndexingJobs"" (""ModuleId"");
    END IF;

    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'core' AND tablename = 'SearchIndexEntries') THEN
        CREATE TABLE core.""SearchIndexEntries"" (
            ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
            ""ModuleId"" varchar(50) NOT NULL,
            ""EntityId"" varchar(64) NOT NULL,
            ""EntityType"" varchar(100) NOT NULL,
            ""Title"" varchar(500) NOT NULL,
            ""Content"" varchar(102400) NOT NULL,
            ""Summary"" varchar(1000) NULL,
            ""OwnerId"" uuid NOT NULL,
            ""OrganizationId"" uuid NULL,
            ""CreatedAt"" timestamptz NOT NULL,
            ""UpdatedAt"" timestamptz NOT NULL,
            ""IndexedAt"" timestamptz NOT NULL,
            ""MetadataJson"" varchar(4000) NULL,
            CONSTRAINT ""PK_SearchIndexEntries"" PRIMARY KEY (""Id"")
        );
        CREATE UNIQUE INDEX ""ix_search_index_module_entity"" ON core.""SearchIndexEntries"" (""ModuleId"", ""EntityId"");
        CREATE INDEX ""ix_search_index_owner_id"" ON core.""SearchIndexEntries"" (""OwnerId"");
        CREATE INDEX ""ix_search_index_organization_id"" ON core.""SearchIndexEntries"" (""OrganizationId"");
        CREATE INDEX ""ix_search_index_module_id"" ON core.""SearchIndexEntries"" (""ModuleId"");
        CREATE INDEX ""ix_search_index_entity_type"" ON core.""SearchIndexEntries"" (""EntityType"");
        CREATE INDEX ""ix_search_index_updated_at"" ON core.""SearchIndexEntries"" (""UpdatedAt"");
    END IF;
END $$;
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "IndexingJobs",
                schema: "core");

            migrationBuilder.DropTable(
                name: "SearchIndexEntries",
                schema: "core");
        }
    }
}
