// <auto-generated />
using System;
using DotNetCloud.Modules.Music.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetCloud.Modules.Music.Data.SqlServer.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20260517233344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("music")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscogsUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEnrichedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MusicBrainzId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OfficialUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SortName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WikipediaUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_artists_is_deleted");

                    b.HasIndex("MusicBrainzId")
                        .HasDatabaseName("ix_artists_musicbrainz_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_artists_name");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_artists_owner_id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_artists_owner_name");

                    b.ToTable("Artists", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.EqPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BandsJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_eq_presets_owner_id");

                    b.HasIndex("OwnerId", "Name")
                        .HasDatabaseName("ix_eq_presets_owner_name");

                    b.ToTable("EqPresets", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_genres_name");

                    b.ToTable("Genres", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.MusicAlbum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverArtPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasCoverArt")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEnrichedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MusicBrainzReleaseGroupId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("MusicBrainzReleaseId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TotalDurationTicks")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_music_albums_artist_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_music_albums_is_deleted");

                    b.HasIndex("MusicBrainzReleaseGroupId")
                        .HasDatabaseName("ix_music_albums_musicbrainz_release_group_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_music_albums_owner_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_music_albums_title");

                    b.HasIndex("Year")
                        .HasDatabaseName("ix_music_albums_year");

                    b.ToTable("Albums", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.PlaybackHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationPlayedSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlayedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_playback_history_track_id");

                    b.HasIndex("UserId", "PlayedAt")
                        .HasDatabaseName("ix_playback_history_user_played_at");

                    b.ToTable("PlaybackHistories", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_playlists_is_deleted");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_playlists_name");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_playlists_owner_id");

                    b.ToTable("Playlists", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.PlaylistTrack", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("PlaylistId", "TrackId");

                    b.HasIndex("TrackId");

                    b.HasIndex("PlaylistId", "SortOrder")
                        .HasDatabaseName("ix_playlist_tracks_playlist_sort");

                    b.ToTable("PlaylistTracks", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.ScrobbleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlbumTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ScrobbledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrackTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_scrobble_records_track_id");

                    b.HasIndex("UserId", "ScrobbledAt")
                        .HasDatabaseName("ix_scrobble_records_user_scrobbled_at");

                    b.ToTable("ScrobbleRecords", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.StarredItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StarredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_starred_items_user_id");

                    b.HasIndex("UserId", "ItemType", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("uq_starred_items_user_type_item");

                    b.ToTable("StarredItems", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("Bitrate")
                        .HasColumnType("bigint");

                    b.Property<int?>("Channels")
                        .HasColumnType("int");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscNumber")
                        .HasColumnType("int");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FileNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEnrichedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MusicBrainzRecordingId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("int");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("ix_tracks_album_id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_tracks_content_hash");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_tracks_is_deleted");

                    b.HasIndex("MusicBrainzRecordingId")
                        .HasDatabaseName("ix_tracks_musicbrainz_recording_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_tracks_owner_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_tracks_title");

                    b.HasIndex("FileNodeId", "OwnerId")
                        .IsUnique()
                        .HasDatabaseName("uq_tracks_file_node_owner_id");

                    b.HasIndex("OwnerId", "CreatedAt")
                        .HasDatabaseName("ix_tracks_owner_created_at");

                    b.ToTable("Tracks", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.TrackArtist", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("TrackId", "ArtistId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_track_artists_artist_id");

                    b.HasIndex("TrackId", "IsPrimary")
                        .HasDatabaseName("ix_track_artists_track_primary");

                    b.ToTable("TrackArtists", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.TrackGenre", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrackId", "GenreId");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_track_genres_genre_id");

                    b.ToTable("TrackGenres", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.UserMusicPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveEqPresetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RepeatMode")
                        .HasColumnType("int");

                    b.Property<bool>("ShuffleEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ActiveEqPresetId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_music_preferences_user_id");

                    b.ToTable("UserMusicPreferences", "music");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.MusicAlbum", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Music.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.PlaybackHistory", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Music.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.PlaylistTrack", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Music.Models.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Music.Models.Track", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.ScrobbleRecord", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Music.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.Track", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Music.Models.MusicAlbum", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.TrackArtist", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Music.Models.Artist", "Artist")
                        .WithMany("TrackArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Music.Models.Track", "Track")
                        .WithMany("TrackArtists")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.TrackGenre", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Music.Models.Genre", "Genre")
                        .WithMany("TrackGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Music.Models.Track", "Track")
                        .WithMany("TrackGenres")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.UserMusicPreference", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Music.Models.EqPreset", "ActiveEqPreset")
                        .WithMany()
                        .HasForeignKey("ActiveEqPresetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveEqPreset");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("TrackArtists");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.Genre", b =>
                {
                    b.Navigation("TrackGenres");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.MusicAlbum", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Music.Models.Track", b =>
                {
                    b.Navigation("PlaylistTracks");

                    b.Navigation("TrackArtists");

                    b.Navigation("TrackGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
