CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Description" character varying(500),
        "IsSystemRole" boolean NOT NULL DEFAULT FALSE,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "DisplayName" character varying(200) NOT NULL,
        "AvatarUrl" character varying(500),
        "Locale" character varying(10) NOT NULL DEFAULT 'en-US',
        "Timezone" character varying(50) NOT NULL DEFAULT 'UTC',
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (GETUTCDATE()),
        "LastLoginAt" timestamp with time zone,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "InstalledModules" (
        "ModuleId" character varying(200) NOT NULL,
        "Version" character varying(50) NOT NULL,
        "Status" character varying(50) NOT NULL,
        "InstalledAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_InstalledModules" PRIMARY KEY ("ModuleId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "Organizations" (
        "Id" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "Permissions" (
        "Id" uuid NOT NULL,
        "Code" character varying(255) NOT NULL,
        "DisplayName" character varying(200) NOT NULL,
        "Description" character varying(1000),
        CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "Roles" (
        "Id" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "IsSystemRole" boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "SystemSettings" (
        module character varying(100) NOT NULL,
        key character varying(200) NOT NULL,
        value character varying(10000) NOT NULL,
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        description character varying(500),
        CONSTRAINT "PK_SystemSettings" PRIMARY KEY (module, key)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "UserDevices" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "DeviceType" character varying(50) NOT NULL,
        "PushToken" character varying(500),
        "LastSeenAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_UserDevices" PRIMARY KEY ("Id"),
        CONSTRAINT fk_user_devices_user_id FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "UserSettings" (
        "Id" uuid NOT NULL,
        user_id uuid NOT NULL,
        key character varying(200) NOT NULL,
        value character varying(10000) NOT NULL,
        module character varying(100) NOT NULL,
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        description character varying(500),
        is_encrypted boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_UserSettings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_user_settings_user_id" FOREIGN KEY (user_id) REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "ModuleCapabilityGrants" (
        "Id" uuid NOT NULL,
        "ModuleId" character varying(200) NOT NULL,
        "CapabilityName" character varying(200) NOT NULL,
        "GrantedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "GrantedByUserId" uuid,
        CONSTRAINT "PK_ModuleCapabilityGrants" PRIMARY KEY ("Id"),
        CONSTRAINT fk_module_capability_grants_granted_by_user_id FOREIGN KEY ("GrantedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT fk_module_capability_grants_module_id FOREIGN KEY ("ModuleId") REFERENCES "InstalledModules" ("ModuleId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "Groups" (
        "Id" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Groups" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Groups_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "OrganizationMembers" (
        "OrganizationId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "RoleIds" jsonb NOT NULL DEFAULT '[]',
        "JoinedAt" timestamp with time zone NOT NULL,
        "InvitedByUserId" uuid,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_OrganizationMembers" PRIMARY KEY ("OrganizationId", "UserId"),
        CONSTRAINT "FK_OrganizationMembers_AspNetUsers_InvitedByUserId" FOREIGN KEY ("InvitedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_OrganizationMembers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrganizationMembers_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "OrganizationSettings" (
        "Id" uuid NOT NULL,
        organization_id uuid NOT NULL,
        key character varying(200) NOT NULL,
        value character varying(10000) NOT NULL,
        module character varying(100) NOT NULL,
        updated_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        description character varying(500),
        "OrganizationId1" uuid,
        CONSTRAINT "PK_OrganizationSettings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrganizationSettings_Organizations_OrganizationId1" FOREIGN KEY ("OrganizationId1") REFERENCES "Organizations" ("Id"),
        CONSTRAINT "FK_organization_settings_organization_id" FOREIGN KEY (organization_id) REFERENCES "Organizations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "Teams" (
        "Id" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Teams" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Teams_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "RolePermissions" (
        "RoleId" uuid NOT NULL,
        "PermissionId" uuid NOT NULL,
        CONSTRAINT "PK_role_permissions" PRIMARY KEY ("RoleId", "PermissionId"),
        CONSTRAINT "FK_role_permissions_permission_id" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_role_permissions_role_id" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "GroupMembers" (
        "GroupId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "AddedAt" timestamp with time zone NOT NULL,
        "AddedByUserId" uuid,
        CONSTRAINT "PK_GroupMembers" PRIMARY KEY ("GroupId", "UserId"),
        CONSTRAINT "FK_GroupMembers_AspNetUsers_AddedByUserId" FOREIGN KEY ("AddedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_GroupMembers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_GroupMembers_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE TABLE "TeamMembers" (
        "TeamId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "RoleIds" jsonb NOT NULL DEFAULT '[]',
        "JoinedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_TeamMembers" PRIMARY KEY ("TeamId", "UserId"),
        CONSTRAINT "FK_TeamMembers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TeamMembers_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_ApplicationRoles_IsSystemRole" ON "AspNetRoles" ("IsSystemRole");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_ApplicationRoles_Name" ON "AspNetRoles" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_ApplicationUsers_DisplayName" ON "AspNetUsers" ("DisplayName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_ApplicationUsers_Email" ON "AspNetUsers" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_ApplicationUsers_IsActive" ON "AspNetUsers" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_ApplicationUsers_LastLoginAt" ON "AspNetUsers" ("LastLoginAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_group_members_added_at" ON "GroupMembers" ("AddedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_group_members_added_by" ON "GroupMembers" ("AddedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_group_members_user_id" ON "GroupMembers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_groups_created_at" ON "Groups" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_groups_is_deleted" ON "Groups" ("IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_groups_org_name" ON "Groups" ("OrganizationId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX ix_installed_modules_installed_at ON "InstalledModules" ("InstalledAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX ix_installed_modules_status ON "InstalledModules" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX ix_module_capability_grants_capability_name ON "ModuleCapabilityGrants" ("CapabilityName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX ix_module_capability_grants_granted_by_user_id ON "ModuleCapabilityGrants" ("GrantedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX ix_module_capability_grants_module_id ON "ModuleCapabilityGrants" ("ModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_module_capability_grants_module_id_capability_name ON "ModuleCapabilityGrants" ("ModuleId", "CapabilityName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_org_members_invited_by" ON "OrganizationMembers" ("InvitedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_org_members_is_active" ON "OrganizationMembers" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_org_members_joined_at" ON "OrganizationMembers" ("JoinedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_org_members_user_id" ON "OrganizationMembers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_organizations_created_at" ON "Organizations" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_organizations_is_deleted" ON "Organizations" ("IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_organizations_name" ON "Organizations" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_organization_settings_module" ON "OrganizationSettings" (module);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_organization_settings_organization_id" ON "OrganizationSettings" (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_organization_settings_unique" ON "OrganizationSettings" (organization_id, module, key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_organization_settings_updated_at" ON "OrganizationSettings" (updated_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_OrganizationSettings_OrganizationId1" ON "OrganizationSettings" ("OrganizationId1");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_permissions_code" ON "Permissions" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_role_permissions_permission_id" ON "RolePermissions" ("PermissionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_role_permissions_role_id" ON "RolePermissions" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_roles_is_system_role" ON "Roles" ("IsSystemRole");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_roles_name" ON "Roles" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_system_settings_module" ON "SystemSettings" (module);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_system_settings_updated_at" ON "SystemSettings" (updated_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_team_members_joined_at" ON "TeamMembers" ("JoinedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_team_members_user_id" ON "TeamMembers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_teams_created_at" ON "Teams" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_teams_is_deleted" ON "Teams" ("IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_teams_org_name" ON "Teams" ("OrganizationId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX ix_user_devices_last_seen_at ON "UserDevices" ("LastSeenAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX ix_user_devices_user_id ON "UserDevices" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX ix_user_devices_user_id_device_type ON "UserDevices" ("UserId", "DeviceType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_user_settings_is_encrypted" ON "UserSettings" (is_encrypted);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_user_settings_module" ON "UserSettings" (module);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_user_settings_unique" ON "UserSettings" (user_id, module, key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_user_settings_updated_at" ON "UserSettings" (updated_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    CREATE INDEX "IX_user_settings_user_id" ON "UserSettings" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260302195528_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260302195528_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

