// <auto-generated />
using System;
using DotNetCloud.Modules.Video.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetCloud.Modules.Video.Data.SqlServer.Migrations
{
    [DbContext(typeof(VideoDbContext))]
    partial class VideoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("video")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.Subtitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_subtitles_video_id");

                    b.HasIndex("VideoId", "Language")
                        .HasDatabaseName("ix_subtitles_video_language");

                    b.ToTable("Subtitles", "video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalPosterPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FileNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Genres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("HasExternalPoster")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEnrichedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Overview")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ThumbnailPoster")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("thumbnail_poster");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("int");

                    b.Property<double?>("TmdbRating")
                        .HasColumnType("float");

                    b.Property<string>("TmdbTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_videos_is_deleted");

                    b.HasIndex("LastEnrichedAt")
                        .HasDatabaseName("ix_videos_last_enriched_at");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_videos_owner_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_videos_title");

                    b.HasIndex("TmdbId")
                        .HasDatabaseName("ix_videos_tmdb_id");

                    b.HasIndex("FileNodeId", "OwnerId")
                        .IsUnique()
                        .HasDatabaseName("uq_videos_file_node_owner_id");

                    b.HasIndex("OwnerId", "CreatedAt")
                        .HasDatabaseName("ix_videos_owner_created_at");

                    b.ToTable("Videos", "video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.VideoCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_video_collections_name");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_video_collections_owner_id");

                    b.ToTable("VideoCollections", "video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.VideoCollectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_collection_items_collection_id");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_collection_items_video_id");

                    b.HasIndex("CollectionId", "VideoId")
                        .IsUnique()
                        .HasDatabaseName("uq_collection_items_collection_video");

                    b.ToTable("VideoCollectionItems", "video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.VideoMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AudioTrackCount")
                        .HasColumnType("int");

                    b.Property<long>("Bitrate")
                        .HasColumnType("bigint");

                    b.Property<string>("ContainerFormat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ExtractedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("FrameRate")
                        .HasColumnType("float");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("SubtitleTrackCount")
                        .HasColumnType("int");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique()
                        .HasDatabaseName("uq_video_metadata_video_id");

                    b.ToTable("VideoMetadata", "video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.VideoShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("SharedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SharedWithUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShareToken")
                        .HasDatabaseName("ix_video_shares_token");

                    b.HasIndex("SharedByUserId")
                        .HasDatabaseName("ix_video_shares_shared_by");

                    b.HasIndex("SharedWithUserId")
                        .HasDatabaseName("ix_video_shares_shared_with");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_video_shares_video_id");

                    b.ToTable("VideoShares", "video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.WatchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationWatchedSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("WatchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_watch_history_user_id");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_watch_history_video_id");

                    b.HasIndex("UserId", "WatchedAt")
                        .HasDatabaseName("ix_watch_history_user_watched_at");

                    b.ToTable("WatchHistories", "video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.WatchProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<long>("PositionTicks")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_watch_progress_user_id");

                    b.HasIndex("VideoId");

                    b.HasIndex("UserId", "VideoId")
                        .IsUnique()
                        .HasDatabaseName("uq_watch_progress_user_video");

                    b.ToTable("WatchProgresses", "video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.Subtitle", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Video.Models.Video", "Video")
                        .WithMany("Subtitles")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.VideoCollectionItem", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Video.Models.VideoCollection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Video.Models.Video", "Video")
                        .WithMany("CollectionItems")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.VideoMetadata", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Video.Models.Video", "Video")
                        .WithOne("Metadata")
                        .HasForeignKey("DotNetCloud.Modules.Video.Models.VideoMetadata", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.VideoShare", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Video.Models.Video", "Video")
                        .WithMany("Shares")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.WatchHistory", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Video.Models.Video", "Video")
                        .WithMany("WatchHistories")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.WatchProgress", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Video.Models.Video", "Video")
                        .WithMany("WatchProgresses")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.Video", b =>
                {
                    b.Navigation("CollectionItems");

                    b.Navigation("Metadata");

                    b.Navigation("Shares");

                    b.Navigation("Subtitles");

                    b.Navigation("WatchHistories");

                    b.Navigation("WatchProgresses");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Video.Models.VideoCollection", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
