<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DotNetCloud.Core.Search</RootNamespace>
    <AssemblyName>DotNetCloud.Core.Search</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DotNetCloud.Core/DotNetCloud.Core.csproj" />
    <ProjectReference Include="../DotNetCloud.Core.Data/DotNetCloud.Core.Data.csproj" />
  </ItemGroup>

</Project>
