// <auto-generated />
using System;
using DotNetCloud.Modules.Files.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetCloud.Modules.Files.Data.Migrations.SqlServer
{
    [DbContext(typeof(FilesDbContext))]
    [Migration("20260304172718_InitialFilesSchema_SqlServer")]
    partial class InitialFilesSchema_SqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.ChunkedUploadSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChunkManifest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReceivedChunks")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("TargetFileNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("int");

                    b.Property<long>("TotalSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_upload_sessions_expires_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_upload_sessions_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_upload_sessions_user_id");

                    b.ToTable("UploadSessions");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChunkHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastReferencedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ReferenceCount")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ChunkHash")
                        .IsUnique()
                        .HasDatabaseName("ix_file_chunks_hash");

                    b.HasIndex("ReferenceCount")
                        .HasDatabaseName("ix_file_chunks_ref_count");

                    b.ToTable("FileChunks");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_file_comments_created_at");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_file_comments_created_by");

                    b.HasIndex("FileNodeId")
                        .HasDatabaseName("ix_file_comments_file_node_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_file_comments_parent_id");

                    b.ToTable("FileComments");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("MaterializedPath")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("OriginalParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_file_nodes_content_hash");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_file_nodes_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_file_nodes_is_deleted");

                    b.HasIndex("MaterializedPath")
                        .HasDatabaseName("ix_file_nodes_materialized_path");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_file_nodes_owner_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_file_nodes_parent_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_file_nodes_updated_at");

                    b.HasIndex("OwnerId", "IsFavorite")
                        .HasDatabaseName("ix_file_nodes_owner_favorite");

                    b.HasIndex("ParentId", "Name")
                        .HasDatabaseName("ix_file_nodes_parent_name");

                    b.ToTable("FileNodes");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastCalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("MaxBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("UsedBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_file_quotas_user_id");

                    b.ToTable("FileQuotas");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FileNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkPasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LinkToken")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("MaxDownloads")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShareType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("SharedWithGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SharedWithTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SharedWithUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_file_shares_created_by");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_file_shares_expires_at");

                    b.HasIndex("FileNodeId")
                        .HasDatabaseName("ix_file_shares_file_node_id");

                    b.HasIndex("LinkToken")
                        .IsUnique()
                        .HasDatabaseName("ix_file_shares_link_token")
                        .HasFilter("[LinkToken] IS NOT NULL");

                    b.HasIndex("SharedWithTeamId")
                        .HasDatabaseName("ix_file_shares_shared_with_team");

                    b.HasIndex("SharedWithUserId")
                        .HasDatabaseName("ix_file_shares_shared_with_user");

                    b.ToTable("FileShares");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_file_tags_created_by");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_file_tags_name");

                    b.HasIndex("FileNodeId", "Name", "CreatedByUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_file_tags_node_name_user");

                    b.ToTable("FileTags");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_file_versions_content_hash");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_file_versions_created_by");

                    b.HasIndex("FileNodeId")
                        .HasDatabaseName("ix_file_versions_file_node_id");

                    b.HasIndex("FileNodeId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_file_versions_node_version");

                    b.ToTable("FileVersions");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileVersionChunk", b =>
                {
                    b.Property<Guid>("FileVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileChunkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SequenceIndex")
                        .HasColumnType("int");

                    b.HasKey("FileVersionId", "FileChunkId", "SequenceIndex");

                    b.HasIndex("FileChunkId");

                    b.HasIndex("FileVersionId", "SequenceIndex")
                        .HasDatabaseName("ix_file_version_chunks_version_seq");

                    b.ToTable("FileVersionChunks");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileComment", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Files.Models.FileNode", "FileNode")
                        .WithMany("Comments")
                        .HasForeignKey("FileNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Files.Models.FileComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FileNode");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileNode", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Files.Models.FileNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileShare", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Files.Models.FileNode", "FileNode")
                        .WithMany("Shares")
                        .HasForeignKey("FileNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileNode");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileTag", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Files.Models.FileNode", "FileNode")
                        .WithMany("Tags")
                        .HasForeignKey("FileNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileNode");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileVersion", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Files.Models.FileNode", "FileNode")
                        .WithMany("Versions")
                        .HasForeignKey("FileNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileNode");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileVersionChunk", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Files.Models.FileChunk", "FileChunk")
                        .WithMany()
                        .HasForeignKey("FileChunkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Files.Models.FileVersion", "FileVersion")
                        .WithMany()
                        .HasForeignKey("FileVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileChunk");

                    b.Navigation("FileVersion");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Files.Models.FileNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Comments");

                    b.Navigation("Shares");

                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
