// <auto-generated />
using System;
using DotNetCloud.Modules.Photos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetCloud.Modules.Photos.Data.SqlServer.Migrations
{
    [DbContext(typeof(PhotosDbContext))]
    partial class PhotosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("photos")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoverPhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_albums_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_albums_is_deleted");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_albums_owner_id");

                    b.ToTable("Albums", "photos");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.AlbumPhoto", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("AlbumId", "PhotoId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("AlbumId", "SortOrder")
                        .HasDatabaseName("ix_album_photos_album_sort");

                    b.ToTable("AlbumPhotos", "photos");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FileNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ThumbnailDetail")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ThumbnailGrid")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_photos_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_photos_is_deleted");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_photos_owner_id");

                    b.HasIndex("FileNodeId", "OwnerId")
                        .IsUnique()
                        .HasDatabaseName("uq_photos_file_node_owner_id");

                    b.HasIndex("OwnerId", "IsFavorite")
                        .HasDatabaseName("ix_photos_owner_favorite");

                    b.HasIndex("OwnerId", "TakenAt")
                        .HasDatabaseName("ix_photos_owner_taken_at");

                    b.ToTable("Photos", "photos");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.PhotoEditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EditedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StackOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId", "StackOrder")
                        .HasDatabaseName("ix_photo_edit_records_photo_order");

                    b.ToTable("PhotoEditRecords", "photos");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.PhotoMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AltitudeMetres")
                        .HasColumnType("float");

                    b.Property<double?>("Aperture")
                        .HasColumnType("float");

                    b.Property<string>("CameraMake")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CameraModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("FlashFired")
                        .HasColumnType("bit");

                    b.Property<double?>("FocalLengthMm")
                        .HasColumnType("float");

                    b.Property<int?>("Iso")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LensModel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("Orientation")
                        .HasColumnType("int");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShutterSpeed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("TakenAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("ix_photo_metadata_geo")
                        .HasFilter("\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL");

                    b.ToTable("PhotoMetadata", "photos");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.PhotoShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SharedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SharedWithUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("ix_photo_shares_album_id");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("ix_photo_shares_photo_id");

                    b.HasIndex("SharedWithUserId")
                        .HasDatabaseName("ix_photo_shares_shared_with");

                    b.ToTable("PhotoShares", "photos");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.PhotoTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Tag")
                        .HasDatabaseName("ix_photo_tags_tag");

                    b.HasIndex("PhotoId", "Tag")
                        .IsUnique()
                        .HasDatabaseName("uq_photo_tags_photo_tag");

                    b.ToTable("PhotoTags", "photos");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.AlbumPhoto", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Photos.Models.Album", "Album")
                        .WithMany("AlbumPhotos")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCloud.Modules.Photos.Models.Photo", "Photo")
                        .WithMany("AlbumPhotos")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.PhotoEditRecord", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Photos.Models.Photo", "Photo")
                        .WithMany("EditRecords")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.PhotoMetadata", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Photos.Models.Photo", "Photo")
                        .WithOne("Metadata")
                        .HasForeignKey("DotNetCloud.Modules.Photos.Models.PhotoMetadata", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.PhotoShare", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Photos.Models.Album", "Album")
                        .WithMany("Shares")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DotNetCloud.Modules.Photos.Models.Photo", "Photo")
                        .WithMany("Shares")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Album");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.PhotoTag", b =>
                {
                    b.HasOne("DotNetCloud.Modules.Photos.Models.Photo", "Photo")
                        .WithMany("Tags")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.Album", b =>
                {
                    b.Navigation("AlbumPhotos");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("DotNetCloud.Modules.Photos.Models.Photo", b =>
                {
                    b.Navigation("AlbumPhotos");

                    b.Navigation("EditRecords");

                    b.Navigation("Metadata");

                    b.Navigation("Shares");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
