using DotNetCloud.Modules.Search.Data;
using DotNetCloud.Modules.Search.Data.Models;
using Microsoft.EntityFrameworkCore;

namespace DotNetCloud.Modules.Search.Tests;

/// <summary>
/// Tests for <see cref="SearchDbContext"/> and entity configurations.
/// </summary>
[TestClass]
public class SearchDbContextTests
{
    private SearchDbContext _db = null!;

    [TestInitialize]
    public void Setup()
    {
        var options = new DbContextOptionsBuilder<SearchDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        _db = new SearchDbContext(options);
    }

    [TestCleanup]
    public void Cleanup()
    {
        _db.Dispose();
    }

    [TestMethod]
    public async Task SearchIndexEntries_CanAddAndRetrieve()
    {
        var entry = new SearchIndexEntry
        {
            ModuleId = "files",
            EntityId = "e1",
            EntityType = "FileNode",
            Title = "Test File",
            Content = "content",
            OwnerId = Guid.NewGuid(),
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow,
            IndexedAt = DateTimeOffset.UtcNow
        };

        _db.SearchIndexEntries.Add(entry);
        await _db.SaveChangesAsync();

        var retrieved = await _db.SearchIndexEntries.FirstAsync();
        Assert.AreEqual("files", retrieved.ModuleId);
        Assert.AreEqual("e1", retrieved.EntityId);
        Assert.AreEqual("Test File", retrieved.Title);
    }

    [TestMethod]
    public async Task SearchIndexEntries_IdAutoGenerated()
    {
        var entry = new SearchIndexEntry
        {
            ModuleId = "files",
            EntityId = "e1",
            EntityType = "FileNode",
            Title = "Test",
            OwnerId = Guid.NewGuid(),
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow,
            IndexedAt = DateTimeOffset.UtcNow
        };

        _db.SearchIndexEntries.Add(entry);
        await _db.SaveChangesAsync();

        Assert.IsTrue(entry.Id > 0);
    }

    [TestMethod]
    public async Task IndexingJobs_CanAddAndRetrieve()
    {
        var job = new IndexingJob
        {
            Type = IndexJobType.Full,
            Status = IndexJobStatus.Pending,
            StartedAt = DateTimeOffset.UtcNow
        };

        _db.IndexingJobs.Add(job);
        await _db.SaveChangesAsync();

        var retrieved = await _db.IndexingJobs.FirstAsync();
        Assert.AreEqual(IndexJobType.Full, retrieved.Type);
        Assert.AreEqual(IndexJobStatus.Pending, retrieved.Status);
        Assert.AreNotEqual(Guid.Empty, retrieved.Id);
    }

    [TestMethod]
    public async Task IndexingJob_StatusTransitions()
    {
        var job = new IndexingJob
        {
            Type = IndexJobType.Full,
            Status = IndexJobStatus.Pending
        };

        _db.IndexingJobs.Add(job);
        await _db.SaveChangesAsync();

        job.Status = IndexJobStatus.Running;
        job.StartedAt = DateTimeOffset.UtcNow;
        await _db.SaveChangesAsync();

        job.Status = IndexJobStatus.Completed;
        job.CompletedAt = DateTimeOffset.UtcNow;
        job.DocumentsProcessed = 100;
        job.DocumentsTotal = 100;
        await _db.SaveChangesAsync();

        var retrieved = await _db.IndexingJobs.FirstAsync();
        Assert.AreEqual(IndexJobStatus.Completed, retrieved.Status);
        Assert.AreEqual(100, retrieved.DocumentsProcessed);
        Assert.IsNotNull(retrieved.CompletedAt);
    }

    [TestMethod]
    public async Task IndexingJob_FailedState_StoresErrorMessage()
    {
        var job = new IndexingJob
        {
            Type = IndexJobType.Incremental,
            Status = IndexJobStatus.Failed,
            ErrorMessage = "Connection timeout"
        };

        _db.IndexingJobs.Add(job);
        await _db.SaveChangesAsync();

        var retrieved = await _db.IndexingJobs.FirstAsync();
        Assert.AreEqual(IndexJobStatus.Failed, retrieved.Status);
        Assert.AreEqual("Connection timeout", retrieved.ErrorMessage);
    }

    [TestMethod]
    public async Task SearchIndexEntry_AllFieldsPersisted()
    {
        var ownerId = Guid.NewGuid();
        var orgId = Guid.NewGuid();
        var createdAt = DateTimeOffset.UtcNow.AddDays(-1);
        var updatedAt = DateTimeOffset.UtcNow;
        var indexedAt = DateTimeOffset.UtcNow;

        var entry = new SearchIndexEntry
        {
            ModuleId = "notes",
            EntityId = "note-42",
            EntityType = "Note",
            Title = "My Note",
            Content = "Note content here",
            Summary = "Short summary",
            OwnerId = ownerId,
            OrganizationId = orgId,
            CreatedAt = createdAt,
            UpdatedAt = updatedAt,
            IndexedAt = indexedAt,
            MetadataJson = """{"tag":"personal"}"""
        };

        _db.SearchIndexEntries.Add(entry);
        await _db.SaveChangesAsync();

        var retrieved = await _db.SearchIndexEntries.FirstAsync();
        Assert.AreEqual("notes", retrieved.ModuleId);
        Assert.AreEqual("note-42", retrieved.EntityId);
        Assert.AreEqual("Note", retrieved.EntityType);
        Assert.AreEqual("My Note", retrieved.Title);
        Assert.AreEqual("Note content here", retrieved.Content);
        Assert.AreEqual("Short summary", retrieved.Summary);
        Assert.AreEqual(ownerId, retrieved.OwnerId);
        Assert.AreEqual(orgId, retrieved.OrganizationId);
        Assert.IsNotNull(retrieved.MetadataJson);
        Assert.IsTrue(retrieved.MetadataJson.Contains("personal"));
    }

    [TestMethod]
    public async Task SearchIndexEntry_NullableFieldsCanBeNull()
    {
        var entry = new SearchIndexEntry
        {
            ModuleId = "files",
            EntityId = "e1",
            EntityType = "FileNode",
            Title = "Test",
            OwnerId = Guid.NewGuid(),
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow,
            IndexedAt = DateTimeOffset.UtcNow,
            Summary = null,
            OrganizationId = null,
            MetadataJson = null
        };

        _db.SearchIndexEntries.Add(entry);
        await _db.SaveChangesAsync();

        var retrieved = await _db.SearchIndexEntries.FirstAsync();
        Assert.IsNull(retrieved.Summary);
        Assert.IsNull(retrieved.OrganizationId);
        Assert.IsNull(retrieved.MetadataJson);
    }

    [TestMethod]
    public async Task IndexingJob_IncrementalType()
    {
        var job = new IndexingJob
        {
            ModuleId = "files",
            Type = IndexJobType.Incremental,
            Status = IndexJobStatus.Completed,
            DocumentsProcessed = 5,
            DocumentsTotal = 5
        };

        _db.IndexingJobs.Add(job);
        await _db.SaveChangesAsync();

        var retrieved = await _db.IndexingJobs.FirstAsync();
        Assert.AreEqual(IndexJobType.Incremental, retrieved.Type);
        Assert.AreEqual("files", retrieved.ModuleId);
    }
}
