namespace DotNetCloud.Core.Server.Configuration;

/// <summary>
/// Provides reverse proxy configuration templates for common web servers.
/// </summary>
public static class ReverseProxyTemplates
{
    /// <summary>
    /// Generates an nginx reverse proxy configuration template.
    /// </summary>
    /// <param name="serverName">The server hostname.</param>
    /// <param name="upstreamPort">The upstream application port.</param>
    /// <param name="enableSsl">Whether to include SSL configuration.</param>
    /// <returns>The nginx configuration template string.</returns>
    public static string GenerateNginxConfig(
        string serverName = "dotnetcloud.example.com",
        int upstreamPort = 5080,
        bool enableSsl = true)
    {
        var sslBlock = enableSsl
            ? """
                listen 443 ssl http2;
                listen [::]:443 ssl http2;
                ssl_certificate /etc/ssl/certs/dotnetcloud.crt;
                ssl_certificate_key /etc/ssl/private/dotnetcloud.key;
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_ciphers HIGH:!aNULL:!MD5;
                ssl_prefer_server_ciphers on;
                ssl_session_cache shared:SSL:10m;
                ssl_session_timeout 10m;
            """
            : "";

        var httpRedirectBlock = enableSsl
            ? $$"""

            server {
                listen 80;
                listen [::]:80;
                server_name {{serverName}};
                return 301 https://$host$request_uri;
            }
            """
            : "";

        return $$"""
            # DotNetCloud nginx reverse proxy configuration
            # Generated by DotNetCloud Server

            upstream dotnetcloud {
                server 127.0.0.1:{{upstreamPort}};
            }

            server {
                listen 80;
                listen [::]:80;
            {{sslBlock}}
                server_name {{serverName}};

                # Proxy settings
                location / {
                    proxy_pass http://dotnetcloud;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection $connection_upgrade;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_set_header X-Forwarded-Host $host;
                    proxy_set_header X-Forwarded-Port $server_port;

                    # Timeouts
                    proxy_connect_timeout 60s;
                    proxy_send_timeout 60s;
                    proxy_read_timeout 60s;

                    # Buffer settings
                    proxy_buffer_size 128k;
                    proxy_buffers 4 256k;
                    proxy_busy_buffers_size 256k;
                }

                # WebSocket support for SignalR
                location /hubs/ {
                    proxy_pass http://dotnetcloud;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;

                    proxy_read_timeout 3600s;
                    proxy_send_timeout 3600s;
                }

                # File upload size limit (matches Kestrel MaxRequestBodySize)
                client_max_body_size 50m;

                # Gzip compression
                gzip on;
                gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
                gzip_min_length 1000;

                # Security headers (handled by the application, but listed for reference)
                # add_header X-Frame-Options "SAMEORIGIN" always;
                # add_header X-Content-Type-Options "nosniff" always;
                # add_header Referrer-Policy "strict-origin-when-cross-origin" always;
            }
            {{httpRedirectBlock}}
            # Required for WebSocket upgrade support
            map $http_upgrade $connection_upgrade {
                default upgrade;
                '' close;
            }
            """;
    }

    /// <summary>
    /// Generates an Apache mod_proxy reverse proxy configuration template.
    /// </summary>
    /// <param name="serverName">The server hostname.</param>
    /// <param name="upstreamPort">The upstream application port.</param>
    /// <param name="enableSsl">Whether to include SSL configuration.</param>
    /// <returns>The Apache configuration template string.</returns>
    public static string GenerateApacheConfig(
        string serverName = "dotnetcloud.example.com",
        int upstreamPort = 5080,
        bool enableSsl = true)
    {
        var sslBlock = enableSsl
            ? """
                SSLEngine on
                SSLCertificateFile /etc/ssl/certs/dotnetcloud.crt
                SSLCertificateKeyFile /etc/ssl/private/dotnetcloud.key
                SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
                SSLCipherSuite HIGH:!aNULL:!MD5
            """
            : "";

        var port = enableSsl ? 443 : 80;

        return $$"""
            # DotNetCloud Apache reverse proxy configuration
            # Generated by DotNetCloud Server
            #
            # Required modules:
            #   a2enmod proxy proxy_http proxy_wstunnel ssl rewrite headers

            <VirtualHost *:{{port}}>
                ServerName {{serverName}}

            {{sslBlock}}
                # Proxy settings
                ProxyPreserveHost On
                ProxyPass / http://127.0.0.1:{{upstreamPort}}/
                ProxyPassReverse / http://127.0.0.1:{{upstreamPort}}/

                # WebSocket support for SignalR
                RewriteEngine On
                RewriteCond %{HTTP:Upgrade} websocket [NC]
                RewriteCond %{HTTP:Connection} upgrade [NC]
                RewriteRule ^/?(.*) ws://127.0.0.1:{{upstreamPort}}/$1 [P,L]

                # Forward headers
                RequestHeader set X-Forwarded-Proto "https" env=HTTPS
                RequestHeader set X-Forwarded-Host %{HTTP_HOST}s
                RequestHeader set X-Forwarded-Port %{SERVER_PORT}s

                # Timeouts
                ProxyTimeout 60
                Timeout 60

                # Error pages
                ErrorLog ${APACHE_LOG_DIR}/dotnetcloud-error.log
                CustomLog ${APACHE_LOG_DIR}/dotnetcloud-access.log combined
            </VirtualHost>
            """;
    }

    /// <summary>
    /// Generates an IIS web.config for ASP.NET Core Module (ANCM) hosting.
    /// </summary>
    /// <param name="processPath">The path to the application executable.</param>
    /// <param name="hostingModel">The hosting model (InProcess or OutOfProcess).</param>
    /// <returns>The web.config XML template string.</returns>
    public static string GenerateIisWebConfig(
        string processPath = "dotnet",
        string hostingModel = "InProcess")
    {
        return $$"""
            <?xml version="1.0" encoding="utf-8"?>
            <!--
              DotNetCloud IIS web.config
              Generated by DotNetCloud Server

              Hosting Model: {{hostingModel}}
              - InProcess: Better performance, runs inside IIS worker process (w3wp.exe)
              - OutOfProcess: Runs as a separate Kestrel process behind IIS reverse proxy
            -->
            <configuration>
              <location path="." inheritInChildApplications="false">
                <system.webServer>
                  <handlers>
                    <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
                  </handlers>
                  <aspNetCore processPath="{{processPath}}"
                              arguments=".\DotNetCloud.Core.Server.dll"
                              stdoutLogEnabled="false"
                              stdoutLogFile=".\logs\stdout"
                              hostingModel="{{hostingModel}}">
                    <environmentVariables>
                      <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Production" />
                      <environmentVariable name="ASPNETCORE_FORWARDEDHEADERS_ENABLED" value="true" />
                    </environmentVariables>
                  </aspNetCore>
                  <security>
                    <requestFiltering>
                      <!-- Match Kestrel MaxRequestBodySize (50MB) -->
                      <requestLimits maxAllowedContentLength="52428800" />
                    </requestFiltering>
                  </security>
                </system.webServer>
              </location>
            </configuration>
            """;
    }

    /// <summary>
    /// Generates an nginx configuration that proxies both DotNetCloud and a Collabora Online server.
    /// </summary>
    /// <param name="serverName">The primary server hostname (for DotNetCloud).</param>
    /// <param name="upstreamPort">The DotNetCloud upstream port.</param>
    /// <param name="collaboraUpstream">
    /// The Collabora Online server address (host:port or full URL, e.g., "127.0.0.1:9980").
    /// If null or empty, the Collabora block is omitted.
    /// </param>
    /// <param name="enableSsl">Whether to include SSL configuration.</param>
    /// <returns>The nginx configuration template string.</returns>
    public static string GenerateNginxConfigWithCollabora(
        string serverName = "dotnetcloud.example.com",
        int upstreamPort = 5080,
        string? collaboraUpstream = "127.0.0.1:9980",
        bool enableSsl = true)
    {
        var baseConfig = GenerateNginxConfig(serverName, upstreamPort, enableSsl);

        if (string.IsNullOrWhiteSpace(collaboraUpstream))
            return baseConfig;

        // Collabora requires specific proxy configuration:
        // - /browser/ serves editor static assets
        // - /hosting/discovery serves the WOPI discovery XML
        // - /cool/ (or /lool/) is the WebSocket endpoint for real-time editing
        var collaboraBlock = $$"""

            # -------------------------------------------------------
            # Collabora Online (CODE) reverse proxy
            # Collabora server: {{collaboraUpstream}}
            # -------------------------------------------------------
            upstream collabora {
                server {{collaboraUpstream}};
            }

            server {
                listen 80;
                listen [::]:80;
            {{(enableSsl ? $"""
                listen 443 ssl http2;
                listen [::]:443 ssl http2;
                ssl_certificate /etc/ssl/certs/dotnetcloud.crt;
                ssl_certificate_key /etc/ssl/private/dotnetcloud.key;
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_ciphers HIGH:!aNULL:!MD5;
            """ : "")}}
                server_name {{serverName}};

                # WOPI discovery (Collabora reads this to register supported formats)
                location /hosting/discovery {
                    proxy_pass https://collabora;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }

                # Collabora capabilities endpoint
                location /hosting/capabilities {
                    proxy_pass https://collabora;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }

                # Collabora editor static assets
                location /browser {
                    proxy_pass https://collabora;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }

                # Collabora real-time WebSocket editing endpoint
                location ~ ^/cool/(.*)/ws$ {
                    proxy_pass https://collabora;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_read_timeout 3600s;
                    proxy_send_timeout 3600s;
                }

                # Collabora admin console WebSocket
                location ^~ /cool {
                    proxy_pass https://collabora;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }
            """;

        return baseConfig + collaboraBlock;
    }

    /// <summary>
    /// Generates an Apache configuration that proxies both DotNetCloud and a Collabora Online server.
    /// </summary>
    /// <param name="serverName">The primary server hostname.</param>
    /// <param name="upstreamPort">The DotNetCloud upstream port.</param>
    /// <param name="collaboraUpstream">The Collabora Online server address (e.g., "https://127.0.0.1:9980").</param>
    /// <param name="enableSsl">Whether to include SSL configuration.</param>
    /// <returns>The Apache configuration template string.</returns>
    public static string GenerateApacheConfigWithCollabora(
        string serverName = "dotnetcloud.example.com",
        int upstreamPort = 5080,
        string? collaboraUpstream = "https://127.0.0.1:9980",
        bool enableSsl = true)
    {
        var baseConfig = GenerateApacheConfig(serverName, upstreamPort, enableSsl);

        if (string.IsNullOrWhiteSpace(collaboraUpstream))
            return baseConfig;

        var port = enableSsl ? 443 : 80;

        var collaboraBlock = $$"""


            # -------------------------------------------------------
            # Collabora Online (CODE) virtual host
            # -------------------------------------------------------
            <VirtualHost *:{{port}}>
                ServerName {{serverName}}

                # Required modules: mod_proxy mod_proxy_http mod_proxy_wstunnel mod_rewrite mod_ssl

            {{(enableSsl ? """
                SSLEngine on
                SSLCertificateFile /etc/ssl/certs/dotnetcloud.crt
                SSLCertificateKeyFile /etc/ssl/private/dotnetcloud.key
                SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
                SSLProxyEngine on
                SSLProxyVerify none
            """ : "")}}
                # WOPI discovery and capabilities
                ProxyPass /hosting/ {{collaboraUpstream}}/hosting/
                ProxyPassReverse /hosting/ {{collaboraUpstream}}/hosting/

                # Collabora editor static assets
                ProxyPass /browser {{collaboraUpstream}}/browser
                ProxyPassReverse /browser {{collaboraUpstream}}/browser

                # Collabora WebSocket real-time editing
                RewriteEngine On
                RewriteCond %{HTTP:Upgrade} websocket [NC]
                RewriteCond %{HTTP:Connection} upgrade [NC]
                RewriteRule ^/cool/(.*)/ws$ wss://{{(collaboraUpstream.StartsWith("https://", StringComparison.OrdinalIgnoreCase) ? collaboraUpstream[8..] : collaboraUpstream)}}/cool/$1/ws [P,L]

                ProxyPass /cool {{collaboraUpstream}}/cool
                ProxyPassReverse /cool {{collaboraUpstream}}/cool

                RequestHeader set X-Forwarded-Proto "https" env=HTTPS
                ProxyTimeout 3600

                ErrorLog ${APACHE_LOG_DIR}/collabora-error.log
                CustomLog ${APACHE_LOG_DIR}/collabora-access.log combined
            </VirtualHost>
            """;

        return baseConfig + collaboraBlock;
    }

    /// <summary>
    /// Validates a reverse proxy configuration by checking required elements.
    /// </summary>
    /// <param name="proxyType">The type of proxy (nginx, apache, iis).</param>
    /// <param name="configContent">The configuration content to validate.</param>
    /// <returns>A validation result with any issues found.</returns>
    public static ReverseProxyValidationResult ValidateConfiguration(string proxyType, string configContent)
    {
        var result = new ReverseProxyValidationResult { ProxyType = proxyType };

        if (string.IsNullOrWhiteSpace(configContent))
        {
            result.Errors.Add("Configuration content is empty.");
            return result;
        }

        switch (proxyType.ToLowerInvariant())
        {
            case "nginx":
                ValidateNginxConfig(configContent, result);
                break;
            case "apache":
                ValidateApacheConfig(configContent, result);
                break;
            case "iis":
                ValidateIisConfig(configContent, result);
                break;
            default:
                result.Errors.Add($"Unknown proxy type: {proxyType}. Supported types: nginx, apache, iis.");
                break;
        }

        return result;
    }

    private static void ValidateNginxConfig(string content, ReverseProxyValidationResult result)
    {
        if (!content.Contains("proxy_pass"))
            result.Errors.Add("Missing 'proxy_pass' directive.");
        if (!content.Contains("proxy_set_header Host"))
            result.Warnings.Add("Missing 'proxy_set_header Host' — the Host header may not be forwarded.");
        if (!content.Contains("X-Forwarded-For"))
            result.Warnings.Add("Missing X-Forwarded-For header forwarding.");
        if (!content.Contains("X-Forwarded-Proto"))
            result.Warnings.Add("Missing X-Forwarded-Proto header forwarding.");
        if (!content.Contains("websocket") && !content.Contains("Upgrade"))
            result.Warnings.Add("No WebSocket upgrade configuration found — SignalR may not work.");

        result.IsValid = result.Errors.Count == 0;
    }

    private static void ValidateApacheConfig(string content, ReverseProxyValidationResult result)
    {
        if (!content.Contains("ProxyPass"))
            result.Errors.Add("Missing 'ProxyPass' directive.");
        if (!content.Contains("ProxyPassReverse"))
            result.Warnings.Add("Missing 'ProxyPassReverse' — redirects may not work correctly.");
        if (!content.Contains("ProxyPreserveHost"))
            result.Warnings.Add("Missing 'ProxyPreserveHost' — the Host header may not be forwarded.");
        if (!content.Contains("ws://") && !content.Contains("wss://"))
            result.Warnings.Add("No WebSocket proxy configuration found — SignalR may not work.");

        result.IsValid = result.Errors.Count == 0;
    }

    private static void ValidateIisConfig(string content, ReverseProxyValidationResult result)
    {
        if (!content.Contains("aspNetCore"))
            result.Errors.Add("Missing 'aspNetCore' handler configuration.");
        if (!content.Contains("AspNetCoreModuleV2"))
            result.Errors.Add("Missing 'AspNetCoreModuleV2' module — ensure ANCM v2 is installed.");
        if (!content.Contains("hostingModel"))
            result.Warnings.Add("Missing 'hostingModel' attribute — defaults to OutOfProcess.");

        result.IsValid = result.Errors.Count == 0;
    }
}

/// <summary>
/// Result of validating a reverse proxy configuration.
/// </summary>
public sealed class ReverseProxyValidationResult
{
    /// <summary>
    /// Gets or sets the proxy type that was validated.
    /// </summary>
    public string ProxyType { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets whether the configuration is valid.
    /// </summary>
    public bool IsValid { get; set; }

    /// <summary>
    /// Gets the list of validation errors.
    /// </summary>
    public List<string> Errors { get; } = [];

    /// <summary>
    /// Gets the list of validation warnings.
    /// </summary>
    public List<string> Warnings { get; } = [];
}
